### ISSUE TITLE
Static_assert failed "Allocator::value_type must be same type as value

### ISSUE THREAD

**Issue by CeadeS** [ygx2011/ORB_SLAM2-IOS#5]
Hello,
when trying to compile this code, my Xcode shows the Static_assert failed "Allocator::value_type must be same type as value in map.cc at line 820. Does it has something to do with my compiler version? I am using Xcode 9.2.

**Comment by barbehenna** [comment]
Hi CeadeS, I encountered the same problem. The fix I came across was to change lines lines 49 and 50 in LoopClosing.h to:
`typedef map<KeyFrame*,g2o::Sim3,std::less<KeyFrame*>,
        Eigen::aligned_allocator<std::pair<KeyFrame* const, g2o::Sim3> > > KeyFrameAndPose;`

**Comment by CeadeS** [comment]
Thank you very much. This works really well. I solved it by unassigning the static asserts to   ;) your solution is much better. Merry Christmas
